user_name = input("Hello, What is your name?: ")
print ()
print ("Hi there " + user_name + "!")
print()
fave_food = input("So tell me, whats your favourite food?: ")
print()
print ("I love " + fave_food + " too!")
print()
where_live = input("And where abouts do you live?: ")
print()
print(where_live + " sounds like a great place!")
print()
print("So, let me get this straight...")
print()
print(user_name + " likes to eat " + fave_food + " in " + where_live + "? Sounds Amaazing!")
print()
print("thanks for speaking to me, youre a star!")

